name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: 'node:20-buster'
    env:
      NO_COLOR: true
    steps:
      - name: Checkouut
        uses: actions/checkout@v4

      - name: Install
        run: npm ci

      - name: Test
        run: npm t;
